### ISSUE TITLE
Minor bugs in the web interface

### ISSUE THREAD

**Issue by vu3vwr** [afarhan/zbitx#11]
Spotted a few minor bugs on the web interface

1. Record function isn't working
2. When the mode is set to PSK or RTTY the radio goes into 2 Tone mode
3. Change the CMD/TEXT field to Text as commands don't work on this field. 
4. Telnet window shifts away as the CW decoder displays the decode. 

<img width="1435" alt="Image" src="https://github.com/user-attachments/assets/0c2b93c4-9a15-4e4b-ba4d-e8757dc98c7e" />

Please see the screenshot.

**Comment by afarhan** [comment]
Fixed in the commit #eb1e8f8, disabled telnet. It was too much of a clutter

**Comment by vu3vwr** [comment]
The option to set the Telnet server is still present on the SET window on the web interface. REC function isn't working. The commands don't seem to work on the CMD window.
